-- Challenge # 1

-- Using the query below create the table for car dealership data.
DROP DATABASE cars_db ;

create database cars_db;

use cars_db;

show tables;

create table car_details (
	sale_id int,
	make char(20),
	type char(20),
	style char(20),
	cost_$ int,
	purchased_date date,
	salesman_id int);

show tables;

insert into car_details(sale_id, make, type, style, cost_$, purchased_date, salesman_id)
values 
	(1, 'Honda', 'Civic', 'Sedan', 40000, '2021-01-01', 1),
	(2, 'Ford', 'Explorer', 'SUV', 35000, '2022-05-02', 2),
	(3, 'Ford', 'Explorer', 'SUV', 25000, '2022-04-01', 3),
	(4, 'Audi', 'A4', 'Sedan', 36000, '2021-05-01', 3),
	(5, 'Honda', 'Civic', 'Sedan', 30000, '2022-08-12', 4),
	(6, 'Nissan', 'Altima', 'Sedan', 48000, '2021-10-06', 2),
	(7, 'Toyota', 'Corolla', 'Hatchback', 40000, '2021-12-31', 1),
	(8, 'Toyota', 'Corolla', 'Hatchback', 60000, '2022-08-25', 1);
    
create table salespersons (
	salesman_id int,
	name char(20),
	age int,
	city char(20));
show tables;
insert into salespersons (salesman_id, name, age, city)
values 
	(1, 'John Smith', 28, 'New York'),
	(2, 'Emily Wong', 35, 'San Franciso'),
	(3, 'Tom Lee', 42, 'Seattle'),
	(4, 'Lucy Chen', 31, 'LA');
    
/* Once the table has been created help Daniel who runs 
a top- end car showroom find some insights in the data. */

show tables;

SELECT * FROM car_details;

SELECT * FROM salespersons;

-- Q. What is the total revenue generated by the sales of “Sedan” cars in each year?
SELECT style, 
		YEAR(purchased_date) AS Year_of_Purchase, 
		SUM(cost_$) AS Total_Revenue
FROM car_details
WHERE style = 'Sedan'
GROUP BY YEAR(purchased_date);

/*2.Challenge #2
Using the dataset from Challenge 1 - 
Write a SQL query to find the top 3 salespeople (salesman_id, name) based on the total sales amount they achieved. 
The result should be sorted in descending order of the total sales amount.
*/
SELECT * FROM car_details;

SELECT * FROM salespersons;

SELECT s.salesman_id , s.name , Sum(c.cost_$) AS `Total_Sales_Amount`
FROM salespersons s INNER JOIN car_details c ON s.salesman_id = c.salesman_id
GROUP BY 1 , 2 
ORDER BY 3 DESC
LIMIT 3 ;

SELECT s.salesman_id , s.name , Sum(c.cost_$) AS `Total_Sales_Amount`
FROM salespersons s INNER JOIN car_details c ON s.salesman_id = c.salesman_id
GROUP BY salesman_id 
ORDER BY Total_Sales_Amount  DESC limit 3 ;
